<a href="https://colab.research.google.com/github/yingyangtongxue/Numerical_Calculus/blob/main/Lista_pratica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def is_symmetrical(M):
    for i in range(len(M)):
        for j  in range(len(M[0])):
            if M[i][j] != M[j][i]:
                return False
    return True

def square(M):
    M = np.array(M)
    if M.shape[0] == M.shape[1]:
      return True
    return False

def is_matrix_positive(M):
  n = np.shape(M)[0] #first row length
  for i in range(n):
    if not M[i][i] > 0:
      return False
  return True

# **Decomposição LU**

In [ ]:
def LU_decomposition(A):
  A = np.array(A,dtype=float) #convert to float list
  U = np.copy(A) 
  n = np.shape(U)[0] #first row length
  L = np.eye(n) #Identity matrix
  for j in np.arange(n-1): # j = row (start -> j=0 in [0,1,...,n-1])
    for i in np.arange(j+1,n): # i = column (start -> i=0 in [j+1,j+2,...,n])
      L[i,j] = U[i,j]/U[j,j] 
      for k in np.arange(j+1,n):
        old = U[i,k]
        U[i,k] = U[i,k] - L[i,j] * U[j,k]
      U[i,j] = 0

  return L,U

1) Escreva uma função em Python para realizar a decomposição LU, e depois teste
seu algoritmo para as seguintes matrizes:

a) A = [[2.0,-1.0,1.0],
     [3.0,3.0,9.0],
     [3.0,3.0,5.0]]

b) A = [[1.012,-2.132,3.104],
      [-2.132,4.906,-7.013],
      [3.104,-7.013,0.014]]

c) A = [[2,0,0,0],
      [1,1.5,0,0],
      [0,-3,0.5,0],
      [2,-2,1,1]]

d) A = [[2.1756,4.0231,-2.1732,5.1967],
        [-4.0231,6.0000,0,1.1973],
        [-1.0000,-5.2107,1.1111,0],
        [6.0235,7.0000,0,-4.1561]]


RESOLUÇÃO:

1-a)

In [ ]:
A = [[2.0,-1.0,1.0],
     [3.0,3.0,9.0],
     [3.0,3.0,5.0]]

print("\nRESULTADO 1-A: \n")

L, U = LU_decomposition(A)

print("\n A = L * U")
print("\nA:\n",A)
print("\nL (Lower Matrix):\n",L)
print("\nU (Upper Matrix):\n",U)


RESULTADO 1-A: 


 A = L * U

A:
 [[2.0, -1.0, 1.0], [3.0, 3.0, 9.0], [3.0, 3.0, 5.0]]

L (Lower Matrix):
 [[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]

U (Upper Matrix):
 [[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]


1-b)

In [ ]:
A = [[1.012,-2.132,3.104],
    [-2.132,4.906,-7.013],
    [3.104,-7.013,0.014]]

print("\nRESULTADO 1-B: \n")

L, U = LU_decomposition(A)

print("\n A = L * U")
print("\nA:\n",A)
print("\nL (Lower Matrix):\n",L)
print("\nU (Upper Matrix):\n",U)


RESULTADO 1-B: 


 A = L * U

A:
 [[1.012, -2.132, 3.104], [-2.132, 4.906, -7.013], [3.104, -7.013, 0.014]]

L (Lower Matrix):
 [[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368 -1.14299746  1.        ]]

U (Upper Matrix):
 [[  1.012       -2.132        3.104     ]
 [  0.           0.41447431  -0.47374308]
 [  0.           0.         -10.04805631]]


1-c)

In [ ]:
A = [[2,0,0,0],
      [1,1.5,0,0],
      [0,-3,0.5,0],
      [2,-2,1,1]]
     
print("\nRESULTADO 1-C: \n")

L, U = LU_decomposition(A)

print("\n A = L * U")
print("\nA:\n",A)
print("\nL (Lower Matrix):\n",L)
print("\nU (Upper Matrix):\n",U)


RESULTADO 1-C: 


 A = L * U

A:
 [[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]]

L (Lower Matrix):
 [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -2.          1.          0.        ]
 [ 1.         -1.33333333  2.          1.        ]]

U (Upper Matrix):
 [[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]


1-d)

In [ ]:
A = [[2.1756,4.0231,-2.1732,5.1967],
        [-4.0231,6.0000,0,1.1973],
        [-1.0000,-5.2107,1.1111,0],
        [6.0235,7.0000,0,-4.1561]]

print("\nRESULTADO 1-D: \n")

L, U = LU_decomposition(A)

print("\n A = L * U")
print("\nA:\n",A)
print("\nL (Lower Matrix):\n",L)
print("\nU (Upper Matrix):\n",U)


RESULTADO 1-D: 


 A = L * U

A:
 [[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0, 0, 1.1973], [-1.0, -5.2107, 1.1111, 0], [6.0235, 7.0, 0, -4.1561]]

L (Lower Matrix):
 [[ 1.          0.          0.          0.        ]
 [-1.84919103  1.          0.          0.        ]
 [-0.45964332 -0.25012194  1.          0.        ]
 [ 2.76866152 -0.30794361 -5.35228302  1.        ]]

U (Upper Matrix):
 [[ 2.1756      4.0231     -2.1732      5.1967    ]
 [ 0.         13.43948042 -4.01866194 10.80699101]
 [ 0.          0.         -0.89295239  5.09169403]
 [ 0.          0.          0.         12.03612803]]


# **Decomposição Cholesky**

2) Escreva uma função em Python para realizar a decomposição Cholesky, e
depois teste seu algoritmo para as seguintes matrizes:

a) A = [[2,-1,0],
      [-1,2,-1],
      [0,-1,2]]

b) A = [[4,1,1,1],
      [1,3,-1,1],
      [1,-1,2,0],
      [1,1,0,2]]

c) A = [[4,1,-1,0],
      [1,3,-1,0],
      [-1,-1,5,2],
      [0,0,2,4]]

d) A = [[6,2,1,-1],
      [2,4,1,0],
      [1,1,4,-1],
      [-1,0,-1,3]]

In [ ]:
def cholesky_decomposition(A):
  A = np.array(A,dtype=float) #convert to float list
  if not square(A):
    print("Error! The matrix isn't square")
  if not (is_matrix_positive(A) and is_symmetrical(A)): # elements above and below the main diagonal must be equal 
    print("Error! The matrix isn't symmetric")
  else:
    n = A.shape[0]
    L = np.zeros_like(A)
    for i in range(n):
        L[i,i] = np.sqrt(A[i,i])
        L[i+1:,i] = A[i+1:,i] / L[i, i]
        for j in range(i+1,n):
            A[j:,j] = A[j:,j] - L[j,i] * L[j:,i]
    return L         

2-a)


In [ ]:
A = [[2,-1,0],
      [-1,2,-1],
      [0,-1,2]]

print("\nRESULTADO 2-A: \n")
A = cholesky_decomposition(A)  
print("\nA:\n",A)  


RESULTADO 2-A: 


A:
 [[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]


2-b)

In [ ]:
A = [[4,1,1,1],
      [1,3,-1,1],
      [1,-1,2,0],
      [1,1,0,2]]

print("\nRESULTADO 2-B: \n")
A = cholesky_decomposition(A)  
print("\nA:\n",A)


RESULTADO 2-B: 


A:
 [[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [ 0.5        -0.75377836  1.08711461  0.        ]
 [ 0.5         0.45226702  0.0836242   1.24034735]]


2-c)

In [ ]:
A = [[4,1,-1,0],
      [1,3,-1,0],
      [-1,-1,5,2],
      [0,0,2,4]]

print("\nRESULTADO 2-C: \n")
A = cholesky_decomposition(A)  
print("\nA:\n",A) 


RESULTADO 2-C: 


A:
 [[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [-0.5        -0.45226702  2.13200716  0.        ]
 [ 0.          0.          0.93808315  1.76635217]]


2-d)

In [ ]:
A = [[6,2,1,-1],
      [2,4,1,0],
      [1,1,4,-1],
      [-1,0,-1,3]]

print("\nRESULTADO 2-D: \n")
A = cholesky_decomposition(A)  
print("\nA:\n",A)


RESULTADO 2-D: 


A:
 [[ 2.44948974  0.          0.          0.        ]
 [ 0.81649658  1.82574186  0.          0.        ]
 [ 0.40824829  0.36514837  1.92353841  0.        ]
 [-0.40824829  0.18257419 -0.46788772  1.60657433]]
